### ISSUE TITLE
Consulta cosas por implementar

### ISSUE THREAD

**Issue by czamoraz** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#10]
Hola!

Tengo una duda acerca de las cosas por implementar en DCChess, porque en el archivo md dice que debemos implementar las reglas necesarias para que el rey pueda llegar a alguna casilla de la fila final sin ser atacada, pero en el archivo solution.lp solamente nos piden las acciones y los movimientos del caballo (junto con los bloqueos de los oponentes). No he analizado el código, solamente fue la primera leída que le di. Mi pregunta es, cuál es el enunciado correcto?

**Comment by dfloreaa** [comment]
Hola, el codigo implementado ya lleva esto a cabo, debe ser una linea que quedo de una version anterior del enunciado (en donde si les pediamos eso, aunque resulto ser muy complejo).

Un saludo y feliz semana ☺️
