### ISSUE TITLE
Consulta bloqueo torres

### ISSUE THREAD

**Issue by Consolo0** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#11]
Hola, tengo este problema que solo me ocurre con las torres, en las cuales de manera muy random de la nada se corta su linea de ataque y por lo que tengo entendido el código de las torres no hay que modificarlo, al igual que el de los peones.

<img width="385" alt="ss dcchess" src="https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/127238882/ae682a14-9f33-4a81-8e0b-3b1f554cf53b">

**Comment by dfloreaa** [comment]
Hola, parece ser un error de nuestro lado, le echare un ojo. De todos modos, si el programa funciona correctamente considerando esas casillas como libres sera corregido como correcto.

Saludos ☺️

**Comment by ignaciovilla** [comment]
Hola! ¿Estas usando un mapa de los ejemplos que entregamos? En ese caso, ¿cuál? 
De lo contrario, puede ser que estés definiendo mal el id de las torres. Fíjate que los id que estas definiendo sean todos distintos.
Avísame si eso lo arregla!

**Comment by Consolo0** [comment]
Hola, estoy usando el map2 y map3 de pawnrook en la carpeta king. Y con respecto a los id de las torres como es un código entregado el cual no debiamos modificar ni lo toque

**Comment by ignaciovilla** [comment]
¿Qué comando estas usando para ejecutar clingo? 
Acabo de revisar y ejecutar los archivos base y funciona bien.
![image](https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/62113032/10dede09-5e9d-43ab-b10e-4e4d9bf64894)

**Comment by Consolo0** [comment]
Ocupo estos

clingo maps/king/pawnRook/map2.lp solution.lp | python3 process.py

clingo maps/king/pawnRook/map3.lp solution.lp | python3 process.py

ocupo python3 porque con python no me funciona

Todo esto estando parado em DCChess

**Comment by KainaBGR** [comment]
Que extraño. Tal vez creaste una regla que influye en los predicados blocked(X,Y). ¿Podrías mencionar las partes que tienes implementadas en tu código solution.lp (sin mostrar el código) para que genere el mapa que mostraste? Habría que analizar en estas partes la manera en que las declaraste, porque podrían tener consecuencias en los bloqueos de las torres.

**Comment by Consolo0** [comment]
No podriamos hacer una reunion super corta en el que enseño mi código? Siento que sería mucho más fácil para ambis

**Comment by Consolo0** [comment]
no importa ya lo arregle, muchas gracias por su tiempo :)

**Comment by KainaBGR** [comment]
Que bueno que pudiste arreglarlo! Gracias por hacernos saber y disculpa por no responder antes.
