### ISSUE TITLE
¿Hay ayudantía hoy (08/04)? 

### ISSUE THREAD

**Issue by SVenegasA** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#12]
Saludos,
Cómo dice el titulo, ¿hay ayudantía hoy? Es que en el modulo de fechas está el día 08/04, sin embargo hasta el día de hoy no está dicho qué cosas se van a ver.

**Comment by dfloreaa** [comment]
Hola, si, hay ayudantia hoy
