### ISSUE TITLE
[Tarea 2] Significado de S en tomar(C,S)

### ISSUE THREAD

**Issue by pedrozavalat** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#13]
Hola!
Tengo una duda con la parte de crear el predicado `tomar(C,S)`. En la parte del enunciado que indican 

> ".. el curso C (indicado por su sigla) se debe tomar en el semestre S (indicado por un numero)..",

 el valor de S es si el curso se dicta en un semestre par, impar o ambos (0, 1 o 2)? o, se refieren al numero del semestre que se toma el curso (que en este caso seria el valor de `bound`)?

Saludos!

**Comment by dfloreaa** [comment]
Hola!

En el contexto del predicado `tomar(C, S)`, `S` corresponde al numero del semestre en que se toma el curso (un valor entero desde `1` hasta `bound`).

Por ejemplo, si tomo el curso `"IIC2613"` en mi quinto semestre, el siguiente predicado debería estar en mi programa: `tomar("IIC2613", 5)` (recuerda que los semestres ya están definidos mediante el predicado `semestre(S)`).

Ojala haya resuelto tu duda, saludos ☺️

**Comment by pedrozavalat** [comment]
Gracias ! 😄
