### ISSUE TITLE
Consulta de test hard

### ISSUE THREAD

**Issue by Nicolas413** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#14]
Tengo una duda con respecto a los tests hard, ya que se requiere de un bound para ejecutar un test, pero en el caso de los hard estos no poseen ninguno, por lo que ¿donde puede encontrar cual es el bound para cada test?

Otra duda, al momento de tener un resultado de un test, se que el modelo cumple las condiciones que piden, pero toma los semestres segun considere que es necesario, en este sentido ¿que clase de resultado esperan del modelo?, ya que al solo optimizar cursos, hay veces que los cursos que son "como seguidos" no se toman todos de corrido, sino que el modelo decide "saltearlos" en otros semestres, cumpliendo los requisitos y correquisitos ligados a estos mismos.

**Comment by dfloreaa** [comment]
Hola, debido a que los test contienen tanta información, no fue posible calcular un `bound `para valores de semestre pequeños (pero que podrían ser factibles, por ejemplo 6 o 7). Por tanto, deberán probar manualmente y revisar que la salida cumpla con las condiciones de requisitos/correquisitos indicadas.

No creo haber entendido tu segunda pregunta, pero mientras se cumplan los requisitos estipulados en el numero de semestres determinado (y se muestren los predicados `tomar(C,S).`) estará todo bien.

Saludos ☺️
