### ISSUE TITLE
[T2] Problema al ejecutar process.py

### ISSUE THREAD

**Issue by Sofiasson** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#15]
Al ejecutar los comandos `clingo maps/.../mapX.lp`, tanto para el rey como para el caballo, no se detectan errores y se informa que los archivos son satisfacibles, por ejemplo:

> clingo maps/king/bishop/map2.lp
> clingo version 5.4.0
> Reading from maps/king/bishop/map2.lp
> Solving...
> Answer: 1
> square(0,0) square(0,1) ... square(9,8) square(9,9) goal(0,9) goal(1,9) ... goal(8,9) goal(9,9) time(0) time(1) ...  time(19) time(20) piece(king) pieceOn(3,5,0) bishop(8,1,0) bishop(3,6,1) bishop(3,4,2) bishop(2,5,3)
> SATISFIABLE
> 
> Models       : 1
> Calls        : 1
> Time         : 0.025s (Solving: 0.01s 1st Model: 0.00s Unsat: 0.01s)
> CPU Time     : 0.000s

Sin embargo, al intentar ejecutar el comando `clingo maps/piece/.../mapX.lp solution.lp | python process.py`, surge un error:

> clingo maps/king/king/map1.lp solution.lp | python process.py
> <cmd>: error: file could not be opened:
>   maps/king/king/map1.lp
> 
> *** ERROR: (clingo): parsing failed
> Traceback (most recent call last):
>   File "process.py", line 77, in <module>
>     answer.board = max(list(map(lambda x: get_numbers(x), list(filter(lambda x: "square" in x, atoms)))))
> 

Me ayudan

**Comment by KainaBGR** [comment]
Hola :) Por lo que veo, clingo no encuentra el mapa indicado "maps/king/king/map1.lp". 
En el repo inicial no existe la carpeta king dentro de king. Si tú creaste una y tienes ese mapa, puede ser otro el error. Estaremos atentos.

**Comment by Sofiasson** [comment]
Gracias, al final me confundi ya que existia `maps/knight/knight/map1.lp` entonces asumi que existía `maps/king/king/map1.lp`, pero no es asi.
