### ISSUE TITLE
[Tarea 2] Parte 3.

### ISSUE THREAD

**Issue by ibgarrido** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#16]
Hola, la 1.5 en el archivo de clingo dice:

> % 1.5 Para un mismo ID de requisito (definido en X_optativo(C, ID)), se debe tomar al menos uno de los cursos

Pero en el enunciado dice:

> % 1.5 Todos los ID de bloques deben tener al menos uno de sus cursos inscritos (o bien se tomo el X necesario o al menos uno de los X optativo)

Cual es la que se debe modelar? la segunda que es más exigente?

**Comment by gaboaurora** [comment]
# Enunciado

## 3.2. Actividad 1: Reglas Básicas

### 5. Todos los ID de bloques deben tener al menos uno de sus cursos inscritos (o bien se tomó el X necesario o al menos uno de los X optativo)

Venía a consultar por la misma parte del enunciado. 

En el archivo clingo se hace referencia a los **requisitos**, se menciona **ID de requisito**, mientras en el enunciado no se mencionan nada de esto, se menciona un **ID de bloque**. 

No entiendo muy bien lo que se pide ¿Podrían dar un ejemplo, o reformular la restricción a modelar, por favor?

**Comment by gaboaurora** [comment]
# Duda extra

Para agregar, otra duda. Están los `pc_necesario` y los `major_necesario`, cada uno con su _Sigla_ y _ID_Bloque_ correspondiente. ¿Mi pregunta es, los cursos de un mismo `ID` quieren significar que pertenecen a un mismo bloque?

Por ejemplo, si tengo el código (_extraído de hard/M258.lp_):

```clingo
pc_necesario("ICS1513", 9).
major_necesario("IIQ2243", 9).
```

¿Entonces, debo elegir solo uno de estos dos, ya que no puede haber más de 1 curso inscrito en el mismo bloque número 9? Me confunde esto, ya que en el enunciado, restricción 3 sale que

> "Se toman todos los cursos X necesarios (para el plan común y major"

¿Esto indicaría que se debe tomar ambos cursos, tanto los `pc_necesario` como los `major_necesario`? 

## Aparte

Como se menciona en los ejemplos, y a su vez observe que solamente los `major_optativo` y los `pc_optativo` se repite el `ID` en los tests, mientras que para los `necesarios`, no se repite el `ID`. ¿Quizás hace referencia a esto esta quinta restricción? 

Por último, para recalcar, si pueden aclarar un poco más sobre los bloques, si hay grupos de bloques, etc.

**Comment by dfloreaa** [comment]
> Hola, la 1.5 en el archivo de clingo dice:
> 
> > % 1.5 Para un mismo ID de requisito (definido en X_optativo(C, ID)), se debe tomar al menos uno de los cursos
> 
> Pero en el enunciado dice:
> 
> > % 1.5 Todos los ID de bloques deben tener al menos uno de sus cursos inscritos (o bien se tomo el X necesario o al menos uno de los X optativo)
> 
> Cual es la que se debe modelar? la segunda que es más exigente?

Hola @ibgarrido, describen exactamente lo mismo. Se busca que se tome al menos un curso para cada ID de curso descrito por plan de estudios (cursos optativos comparten el mismo ID, por eso se le llama "bloque")

**Comment by dfloreaa** [comment]
> # Duda extra
> Para agregar, otra duda. Están los `pc_necesario` y los `major_necesario`, cada uno con su _Sigla_ y _ID_Bloque_ correspondiente. ¿Mi pregunta es, los cursos de un mismo `ID` quieren significar que pertenecen a un mismo bloque?
> 
> Por ejemplo, si tengo el código (_extraído de hard/M258.lp_):
> 
> ```
> pc_necesario("ICS1513", 9).
> major_necesario("IIQ2243", 9).
> ```

Hola @gaboaurora, no, son ID separados ya que es el identificador de requisito para el plan de estudios. Puedes interpretarlo como que para aprobar el plan comun, debo tomar al menos un curso de cada ID de sus bloques descritos (ya sea `pc_necesario(C, ID)` o `pc_optativo(C, ID)`). Similar es el caso para el major.

Saludos

**Comment by dfloreaa** [comment]
> ## Aparte
> Como se menciona en los ejemplos, y a su vez observe que solamente los `major_optativo` y los `pc_optativo` se repite el `ID` en los tests, mientras que para los `necesarios`, no se repite el `ID`. ¿Quizás hace referencia a esto esta quinta restricción?
> 
> Por último, para recalcar, si pueden aclarar un poco más sobre los bloques, si hay grupos de bloques, etc.

Por ejemplo, si miramos el plan de estudios del Major en Ingenieria Robotica
![image](https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/62019645/98650256-b66a-4436-a7af-5b43821d0d83)

Notamos que algunos bloques tienen un curso obligatorio de ser tomado (serian del tipo `major_necesario(C, ID)`), con `ID` siendo el indicador del bloque en particular en el plan de estudios.

En el caso de los cursos electivos (en este caso tenemos dos bloques de cursos electivos), cada bloque tiene una lista de cursos para ser tomados, cada uno de ellos esta descrito como `major_optativo(C1, ID)`, `major_optativo(C2, ID)`, (...). La idea es que todos los cursos posibles a tomar como electivos para ese bloque estan modelados bajo el mismo id **para el Major** (en PC tiene sus propios bloques con sus propios IDs).

Espero que quede mas claro, saludos ☺️

**Comment by gaboaurora** [comment]
Ahí me quedo más claro. Gracias @dfloreaa! 🧠
