### ISSUE TITLE
T2 Parte 3 actividad 2.

### ISSUE THREAD

**Issue by Rodrijzs** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#17]
Hola, en la parte donde se deben implementar los subrequisitos no me queda muy claro cual es el objetivo de los predicados que se piden, por ejemplo para el subrequisito 3:

Se determina req3(c1,idx1,idx2), esto indicaría que para el curso c1 con esos ids se cumple el subrequisito 3 o que c1 DEBE cumplir con ese subrequisito?

**Comment by dfloreaa** [comment]
Hola, se refiere a lo primero, que para el curso C1 se cumple el subrequisito 3 (que es necesario para modelar el subrequisito 2, que a su vez es necesario para modelar el subrequisito 1, que es necesario para tomar el curso).

Lo se, es medio enredado.

Saludos ☺️
