### ISSUE TITLE
T2 P3: bloques y semestres

### ISSUE THREAD

**Issue by pepinofdz** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#19]
Hola! No me queda muy claro que es exactamente un bloque en relación a los cursos necesarios de PC y Major. No corresponden a un semestre? O es un grupo de ramos que pueden ser tomados independiente del semestre? Es posible que tenga que tomar un ramo necesario de un bloque y que adicionalmente pueda tomar un optativo?

Cualquier aclaración se agradece

**Comment by dfloreaa** [comment]
Hola, te recomiendo revisar la issue #16 donde se comenta al respecto. Si tienes mas dudas, dejalas por aqui.

Saludos ☺️
