### ISSUE TITLE
[Tarea 1] Sistema 1 y Sistema 2

### ISSUE THREAD

**Issue by jean-Philipe** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#2]
Hola!, tengo una duda respecto a lo que se pide en la tarea 1, ya que en el final de la tarea se nos pide mencionar respecto a los sistemas involucrados en la idea que estamos describiendo, es decir, si se usa sistema 1 o sistema 2, pero mi duda es, está preguntando sobre cómo usamos nosotros los humanos esos sistemas para solucionar el problema descrito sin IA o está preguntando qué sistema podría utilizar la IA para solucionar el problema? (en el segundo caso me parece un tanto raro, ya que la IA no es capaz de utilizar el sistema 1).

Agradecido con cualquier respuesta :D

**Comment by dfloreaa** [comment]
Hola, hace referencia a que sistemas crees que los humanos usaríamos para resolver estos problemas, (ojo que la IA no es inherentemente sistema 2)
