### ISSUE TITLE
T2 P3: satisfacibilidad

### ISSUE THREAD

**Issue by pepinofdz** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#20]
Hola! Existe algún comando para saber que reglas están haciendo un conflicto de insatisfacibilidad? Por ejemplo, si tengo un programa a.lp que tiene

p:-q
p:-not q

si ejecuto clingo a.lp sólo dice insatisfacible.

Existe algún comando que entregue las reglas que al combinarlas dan insatisfacible? Algo como

clingo a.lp -info=true

que imprima

line 1 incompatible with line 2
line 1 -> p:-q
line 2 -> p:- not q

o algo por el estilo?

Gracias de antemano!

**Comment by dfloreaa** [comment]
Hola, lamentablemente no, esto es debido a como clingo encuentra los modelos por detras. Deberas revisar a mano comentando distintas reglas hasta descubrir la que genera problemas.

Saludos ☺️
