### ISSUE TITLE
T2 P3: Duda con respecto al enunciado

### ISSUE THREAD

**Issue by SVenegasA** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#21]
Saludos,
En la actividad 1 cuando dice "Cada curso puede tomarse solo una vez" ¿se refiere a tomarse en el semestre o en toda la carrera?. Segundo, cursos_pc(0...M) ¿Representa la cantidad de cursos a tomarse en el semestre que se viene o más allá?. Tercero, ¿alguna pista para hacer la actividad 1?

**Comment by SVenegasA** [comment]
Ya resolví esa duda, para mi pregunta 1 la respuesta es que se refiere a toda la carrera, mi pregunta 2, cursos_pc se refiere a toda la carrera también. Pero ahora me surgió otra, ¿Qué cosa es exactamente un bloque? ¿Es un bloque una casilla en cada semestre columna?

**Comment by dfloreaa** [comment]
Hola, por favor revisa la issue #16 al respecto, en la issue #19 tambien lo preguntan (les recomiendo leer las issues antes de abrir unas nuevas), de todos modos, si tienes mas dudas al respecto o no queda claro me avisas por aqui ☺️✨
