### ISSUE TITLE
[T3] Inputs del algoritmo A*  

### ISSUE THREAD

**Issue by Sofiasson** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#23]
Me esta costando entender como aplicar el algoritmo A* en la tarea 3, parte 2:
```
Algoritmo A*
Input: Un problema de búsqueda (S, A, s0, G)
Output: Un nodo objetivo
1 for each s ∈ S do g(s) ← ∞
2 Open ← {s0}
3 g(s0) ← 0; f (s0) ← h(s0)
4 while Open ̸= ∅
5 Extrae un u desde Open con menor valor-f
6 if u es objetivo return u
7 for each v ∈ Succ(u) do
8 Insertar v
```

Entiendo que:
- s0 -> estado inicial 
- G -> conjunto estados objetivo
- S -> El conjunto de todos los posibles estados del problema

Pero en la tarea base solo tiene inputs s0 y G:
`def a_star(s_init, s_goal)`

Es posible agregarle S como input a `a_star`y que `main.py` sea editado acorde a este cambio?

**Comment by dfloreaa** [comment]
Hola, no es necesario tener un S para ejecutar el algoritmo, en su lugar, puedes poblar Open con los sucesores de cada nodo.
Una forma de hacerlo es tener un diccionario con nodos como llaves, en donde nodos nuevos tienen valor-g igual a infinito (cuando son "descubiertos")

Saludos, espero haberte clarificado tu duda ☺️

**Comment by franfonte** [comment]
Es posible saltarme el paso 1 del algoritmo visto en clases? "for each s ∈ S do g(s) ← ∞". Ya que en realidad voy a ir expandiendo los estados individualmente y ahí asignándole sus respectivos costos, por lo que no necesito tener todo el espacio S de antemano

**Comment by dfloreaa** [comment]
> Es posible saltarme el paso 1 del algoritmo visto en clases? "for each s ∈ S do g(s) ← ∞". Ya que en realidad voy a ir expandiendo los estados individualmente y ahí asignándole sus respectivos costos, por lo que no necesito tener todo el espacio S de antemano

Si @franfonte, no hay problema
