### ISSUE TITLE
Dudas T3

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#24]
Buenas tardes! Tengo un par de consultas:

En la parte 2.1, en la implementación del algoritmo A*, qué heuristica tenemos que usar?
En 2.2, se nos pide reportar el tiempo de busqueda y todo eso para cada heuristica. Asumo que se refiere al uso del Algoritmo A* con cada heuristica pedida implementada; pero no entiendo como se hace si A* no recibe un parámetro de heurística
Lo último de 2, en 2.2 cuando se nos pide hacer las tablas para cada mapa con cada heurística; se refiere a que funcione para todos los mapas verdad? 

Gracias de antemano :)

**Comment by dfloreaa** [comment]
Hola, en 2.2 les pedimos implementar las heurísticas Manhattan/2 y Euclidiana/2. Es con estas que deben ejecutar su algoritmo.

TIP: Si usan heurística = 0 el algoritmo también retornara la solución optima, aunque probablemente le tome mas expansiones.
Saludos ☺️

**Comment by TomasRiquelme** [comment]
En "Es con estas que deben ejecutar su algorimot"; entonces la heuristica usada en A* sería la suma de ambas?

**Comment by dfloreaa** [comment]
No, cada una por su cuenta. 

Saludos

**Comment by TomasRiquelme** [comment]
y como sería cada una por su cuenta dentro del mismo algoritmo :0?
Hago dos algoritmos A* y cada uno con su heuristica respectiva?

**Comment by dfloreaa** [comment]
Debes hacer dos ejecuciones distintas, cada una usando una heurística, si.

Puedes entregarle un parámetro a tu función que le indique que heurística utilizar y hacer dos búsquedas distintas o simplemente cambiarlo para dos ejecuciones de tu codigo.

Saludos

**Comment by TomasRiquelme** [comment]
yaaaaaaaaaa perfe. Muchisimas gracias Dani, me salvaste la vida
