### ISSUE TITLE
Duda T3

### ISSUE THREAD

**Issue by LlanosUC** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#25]
Hola! Según el enunciado de la tarea en DCCheckers se debe implementar el algoritmo minimax en el archivo algorithm.py el cual debiese tener comentarios incluidos según la estructura. Sin embargo, solo existe el archivo minimax.py que no tiene más comentarios que los referentes a implementar la poda alfa-beta. ¿Debemos implementar el código del algoritmo en el archivo minimax.py? 

Muchas gracias ^^

**Comment by dfloreaa** [comment]
Hola @LlanosUC, aparentemente subimos una variante antigua del enunciado al repositorio del curso. No deben implementar el algoritmo. Mandare un anuncio al respecto luego.

Saludos ☺️✨
