### ISSUE TITLE
[T3-P1.2] Duda sobre el peso sobre h

### ISSUE THREAD

**Issue by SVenegasA** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#26]
Saludos,
Viendo el vídeo me dí cuenta de que hay muchas cosas que se pueden ocupar, pero tengo cierta duda sobre w, este valor ¿Qué propiedades debe cumplir?¿Puede ser un número racional?

**Comment by dfloreaa** [comment]
Hola, si tiene sentido para la naturaleza del problema, si, los costos pueden ser un numero racional.
