### ISSUE TITLE
[T3] Duda sobre la distancia manhattan y euclidiana dividida en 2 

### ISSUE THREAD

**Issue by ibgarrido** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#27]
Hola! para la implementación de estas heurísticas debo considerarlas como enteros o también pueden tomar valores float dado el contexto del juego pacman en el DCComilon?

**Comment by dfloreaa** [comment]
Hola, puedes considerarlo como un entero, truncando el valor del float (Python lo hace por defecto si usas la division entera `//`)
Saludos ☺️
