### ISSUE TITLE
[T3] condición no trivial de h

### ISSUE THREAD

**Issue by franfonte** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#28]
con condición no trivial de h se refieren a no decir que h = 0?, que h sea admisible por ejemplo seria no trivial?

**Comment by dfloreaa** [comment]
No trivial se trataría de un caso muy particular en donde ocurriese (por ejemplo, si h = 0 permitiese obtener la solución optima). Busquemos que identifiquen una propiedad que h debe cumplir para retornar una solución optima.

Saludos ☺️✨
