### ISSUE TITLE
[T3-2] ¿Es posible que nosotros creemos estructuras para apoyar al desarrollo?

### ISSUE THREAD

**Issue by SVenegasA** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#29]
Saludos,
Mi pregunta es sobre si podemos crear nuestras propias clases para crear las funciones, esto ya que yo sepa la cola FIFO no está implementada en python de por sí
gracias de antemano

**Comment by dfloreaa** [comment]
Claro que si! Saludos ☺️✨
