### ISSUE TITLE
[Tarea 1] Trabajo a futuro parte (c)

### ISSUE THREAD

**Issue by yampaidelimon** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#3]
Hola :)
Para la sección (c), ¿debo justificar cómo mis habilidades se alinean con las tres problemáticas identificadas o solamente con aquella que elegí para desarrollar en detalle? Además, respecto al requisito de las 300 palabras, ¿esta extensión se aplica a la totalidad de la respuesta o únicamente a la sección que explica la importancia de la problemática escogida?

**Comment by dfloreaa** [comment]
Hola, debes explicar cómo todas esas habilidades son utiles para trabajar la problematica en al menos 300 palabras, aparte del la explicacion de cada una de ellas.

Por tanto es tus habilidades + la explicacion de al menos 300 palabras

Saludos
