### ISSUE TITLE
T3 P2.1

### ISSUE THREAD

**Issue by Rodrijzs** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#31]
Hola, no me queda muy claro que es exactamente lo que hace la función ya implementada get_cost.

Esta entrega el costo de ir desde el nodo actual hasta el nodo que uno le entrega pero esto podría tener varios posibles caminos, te estaría entregando el optimo?
Por otro lado tampoco me queda muy claro si existe alguna forma de saber el tamaño del mapa para ir guardando las posiciones con sus respectivos costos.

Gracias!

**Comment by Rodrijzs** [comment]
Otra duda que me surgió, según el algoritmo para A* subido en la ayudantía no me queda muy claro que significaría el return señalado en este paso (adjunto la imagen), lo que imagino es que señala como "si no se cumple esta condición no tomes en cuenta ese sucesor" pero en caso de ser esto entiendo que el if debería ser cost > g(v) en vez de >=

Además en la penúltima linea a que se refiere con reordenar Open?
![astar](https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/127438494/89264276-2134-44be-a0b3-1c28aa0526c5)

**Comment by dfloreaa** [comment]
> Hola, no me queda muy claro que es exactamente lo que hace la función ya implementada get_cost.
> 
> Esta entrega el costo de ir desde el nodo actual hasta el nodo que uno le entrega pero esto podría tener varios posibles caminos, te estaría entregando el optimo? Por otro lado tampoco me queda muy claro si existe alguna forma de saber el tamaño del mapa para ir guardando las posiciones con sus respectivos costos.
> 
> Gracias!

@Rodrijzs la funcion computa el costo del camino hasta el nodo actual, esto se hace navegando hacia su padre recursivamente hasta no encontrar uno mas (es decir, el nodo raiz, desde uno comienza). El costo entonces depende de como hemos navegado hasta ese nodo y no es fijo.

**Comment by dfloreaa** [comment]
> Otra duda que me surgió, según el algoritmo para A* subido en la ayudantía no me queda muy claro que significaría el return señalado en este paso (adjunto la imagen), lo que imagino es que señala como "si no se cumple esta condición no tomes en cuenta ese sucesor" pero en caso de ser esto entiendo que el if debería ser cost > g(v) en vez de >=
> 
> Además en la penúltima linea a que se refiere con reordenar Open? ![astar](https://private-user-images.githubusercontent.com/127438494/329796107-89264276-2134-44be-a0b3-1c28aa0526c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjQ2NDMsIm5iZiI6MTcxNTYyNDM0MywicGF0aCI6Ii8xMjc0Mzg0OTQvMzI5Nzk2MTA3LTg5MjY0Mjc2LTIxMzQtNDRiZS1hMGIzLTFjMjhhYTA1MjZjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxODE5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTIzYTVhMjg0ZDZkN2I1NGM3NzhlYTIyZWVhY2QyOGZiNTdlNDU3ZmU0OTUwZTNjZjdmOGQwOGQ1MjUyMjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9K3Jg9nNTi2aY92TSEv3ub5DIoek9ShZvJg3oef-Emk)

@Rodrijzs el return que indicas es mas como un "continue" y busca no actualizar el costo de llegada a un nodo si es mayor al mejor costo que se ha encontrado para llegar a este anteriormente. Debemos reordenar open dado que actualizamos los valores f de nuestros nodos, reordenandolo para que nodos de menor f sean extraidos antes.
