### ISSUE TITLE
implementación A*

### ISSUE THREAD

**Issue by VicenteGarayR** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#32]
Hola buenas, tengo una duda sobre la implementación de A*

Ya que se pide comparar ambas heuristicas, pero no se pueden mostrar en pantalla ambas, por lo tanto no se si: hacer yo las pruebas y en el pdf explicar la comparación (cambiando la heuristica en el codigo), calcular dos veces el algoritmo y después solo mostrar el que se demora menos o el de menor costo?, la verdad es que no se que hacer con eso, si me pueden ayudar estaría agradecido

**Comment by dfloreaa** [comment]
Hola, si deseas, crea un nuevo pacman y usalo para visualizar ambas heuristicas (spoiler: encuentran el mismo camino, el optimo, pero en tiempos distintos).

**Comment by dfloreaa** [comment]
En todo caso, los mapas son siempre los mismos y no hay componentes aleatorios en el algoritmo, así que puedes hacer múltiples ejecuciones y compararlas entre si.

Saludos! ☺️

**Comment by VicenteGarayR** [comment]
okey, muchas gracias

**Comment by Trycoz** [comment]
Hola, tenía una duda similar... termine agregando un input de heurística a la función de A* (para no repetir 2 veces el mismo codigo de A* con diferentes heurísticas). Lo hice para poder imprimir los resultados de las 2 búsquedas (con heurística euclidiana y manhattan) en la consola. En la visualización se muestra solo el pacman que usa la heurística manhattan (de igual manera es el mismo camino). Quería saber si hacer este cambio en el main (lo de agregar el input a la función a* ) es legal.

Saludos!🤠

**Comment by dfloreaa** [comment]
> Hola, tenía una duda similar... termine agregando un input de heurística a la función de A* (para no repetir 2 veces el mismo codigo de A* con diferentes heurísticas). Lo hice para poder imprimir los resultados de las 2 búsquedas (con heurística euclidiana y manhattan) en la consola. En la visualización se muestra solo el pacman que usa la heurística manhattan (de igual manera es el mismo camino). Quería saber si hacer este cambio en el main (lo de agregar el input a la función a* ) es legal.
> 
> Saludos!🤠

Hola, claro que si! Saludos ☺️✨
