### ISSUE TITLE
MiniMax

### ISSUE THREAD

**Issue by erwannbla** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#33]
Hola,
En la actividad 2 de la parte Checkers, cambiar las profundidades para los algoritmos MiniMax (White vs Black) no cambia nada al resultado.... es normal o problema mio ? (no he cambiado nada excepto las profundidades)
Gracias de antemano

**Comment by dfloreaa** [comment]
Hola, es posible, parece que el algoritmo de Montecarlo es muy bueno... 😅, te recomiendo comentarlo en tu entrega y enfocarte en la naturaleza de la búsqueda (principalmente el tiempo).

Saludos ☺️

**Comment by erwannbla** [comment]
Hola, ok gracias. De hecho mi pregunta era mas sobre MiniMax vs MiniMax donde cambiar la profundidad no cambia nada al resultado y me parece raro...

**Comment by LlanosUC** [comment]
Holaa, a mi igual me pasa lo mismo, se me hace raro que los resultados sean tan similares con profundidades distintas 😿

**Comment by erwannbla** [comment]
Sii, no entiendo...
Ademas cuando ejecuto MCTS contra Minimax con prufundidad 3 el juego no termina (lo dejo correr por más de 15 min) parece que hay un estado de juego atractivo que los algoritmos siguen repitiendo

**Comment by dfloreaa** [comment]
Hola, es posible que así sea y debe estar altamente vinculado a la función de valor utilizada por el algoritmo. Con tal de que reporten estos resultados y **lo que debería ocurrir** se va a considerar como cumplido el objetivo de la pregunta.
