### ISSUE TITLE
[T3] Visualización DCComilon

### ISSUE THREAD

**Issue by Pabloleiva00** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#35]
Hola, he tenido algunos problemas con probar la tarea, específicamente en la visualización de DCComilon. Por ello ¿Cuál es la manera correcta de ejecutar los archivos para ver la visualización?

Muchas gracias de antemano.

**Comment by dfloreaa** [comment]
Hola, deberías solamente correr el archivo ```main.py``` y que la visualización funcione, podrías compartir el error que te aparece?

Un saludo ☺️
