### ISSUE TITLE
[T3] Duda sobre tablas

### ISSUE THREAD

**Issue by Trycoz** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#36]
Hola!

Solo para estar seguro, las tablas para comparar los algoritmos de búsqueda son los que imprimimos en la terminal? o tenemos que agregarlas al pdf?

Saludos!

**Comment by dfloreaa** [comment]
Hola, tienen que estar en el PDF, con resultados promedio, no solamente pantallazos.

Saludos ☺️
