### ISSUE TITLE
[T3] 2.3: Implementación RBFS

### ISSUE THREAD

**Issue by javisanh** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#37]
Hola!
Tengo un par de dudas sobre la implementación,

- ¿Qué heurística hay que considerar para el cálculo del costo en RBFS?
- ¿Qué valor es la cota superior (bounded overhead)? Denotada en el pseudocódigo como B, pero no entiendo muy bien su origen. El paper lo define como "el menor valor-f  de algún nodo inexplorado existente en el espacio de búsqueda", pero no me queda claro cómo definir su inicialización dado que no sé cómo obtener el menor valor f de un nodo desconocido.

Muchas gracias de antemano!

**Comment by dfloreaa** [comment]
Hola, cualquier heuristica sirve, si prefieres, utiliza la distancia Manhattan. Respecto a B, pueden crear un diccionario con todos los nodos y almacenar el f-value para ellos como B al inicializar el algoritmo, este seria entregado como parametro a su ejecucion recursiva. La verdad es que la implementacion queda abierta a lo que mas te acomode siempre y cuando se cumpla el componente distintivo del algoritmo (ser recursivo y best-first)

Un saludo ☺️

**Comment by pepinofdz** [comment]
Hola! Entonces basta con que sea recursivo y best first? Me enredó un poco la implementación por lo que llegué a un algoritmo que cumple con esos dos criterios pero no es óptimo. Da lo mismo? O la optimalidad es importante para la parte de RBFS?

Gracias de antemano!
