### ISSUE TITLE
visualizacion DCComilon

### ISSUE THREAD

**Issue by adribastiasm** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#38]
Hola! Ayer cuando corría mi código de DCComilon me funcionaba bien la visualización del mapa y todo, pero después hice un commit y ahora no me sale la visualización, y tampoco he cambiado nada en el main (a no ser que borré algo de casualidad, pero vi mi historial y sigue igual que cuando me funcionaba).
Por si podrían ayudarme a ver que pasó.
Saludoss.

**Comment by dfloreaa** [comment]
Hola, podrias compartir el mensaje de error que aparece al abrir la visualizacion? Probablemente tenga que ver con el formato de retorno de tu implementacion.

Saludos ☺️

**Comment by adribastiasm** [comment]
Esque no me sale ningún error, de hecho aparece como si supuestamente se abriera la ventana, pero no se ve nada.
<img width="808" alt="Captura de Pantalla 2024-05-15 a la(s) 16 26 27" src="https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/127433914/5ab5f600-366d-4e44-9a59-6db31c58a88e">

**Comment by Pabloleiva00** [comment]
> Hola, podrias compartir el mensaje de error que aparece al abrir la visualizacion? Probablemente tenga que ver con el formato de retorno de tu implementacion.
> 
> Saludos ☺️

Tengo exactamente el problema del compañero de arriba, ejecuto main.py, aparece el icono de pygame, se queda ejecutando, y luego simplemente se acaba la ejecución.

**Comment by nonoam** [comment]
Tuve exactamente el mismo problema. Lo pude solucionar agregando el código que aparece en el siguiente link de stackoverflow https://gamedev.stackexchange.com/questions/181222/why-is-my-program-not-responding-when-i-run-it.

Eso sí, hay que agregar el código en el archivo de `visualization.py`.

**Comment by adribastiasm** [comment]
sigue sin funcionarme con el código de arriba
