### ISSUE TITLE
[T3] Duda implementación A´

### ISSUE THREAD

**Issue by slawhs** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#41]
Hola! Tengo una duda: Para implementar A* y RBFS podemos modificar otros archivos, como la clase Cell que nos entregan en el main.py o los parametros que recibe RBFS en main.py?

**Comment by dfloreaa** [comment]
Hola, no, solamente implementar el algoritmo en el archivo `search.py`

**Comment by slawhs** [comment]
pero no sería necesario para inicializar el g(nodo) en infinito al comienzo tener un atributo que sea nodo.g? o en RBFS para almacenar el valor actual de F
