### ISSUE TITLE
[T3] No puedo visualizar DCComilon

### ISSUE THREAD

**Issue by Naktraker** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#42]
Buenas tardes, esperando que se encuentre bien, realizó este post porque tengo el siguiente problema:

He intentado durante varias horas probar los archivos de DCComilion, tras lo cual en un principio debí cambiar una ruta en el archivo de visualización.py, el cual es el siguiente:
#path_map = "DCComilon/tests/test_4.txt" (original)
 path_map = "/Users/ignaciobarrientos/Documents/PUC/04IA/Tarea-3/T3-main/DCComilon/tests/test_4.txt" (nuevo)

puesto que sin aquel cambio me indicaba un error de que no encontraba la ruta. No obstante, al intentar correr el archivo main.py se ejecuta y me entrega los resultados del DFS, pero no me aparece nada en la ventana de pygame (aparece que se abre, pero luego se cierra sola sin mostrar nada). El código que se ejecuta muestra lo siguiente:

ignaciobarrientos@MacBook-Pro-de-Ignacio DCComilon % /usr/local/bin/python3 /Users/ignaciobarrientos/Documents/PUC/04IA/
Tarea-3/T3-main/DCComilon/main.py
pygame 2.5.2 (SDL 2.28.3, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html

DFS
----------
Tiempo de ejecución: 0.6802780001 ms
Número de expansiones: 197
Largo del camino encontrado: 155
Costo total del camino: 163.5

Inverted DFS
----------

BFS
----------

RBFS
----------

A*
----------
2024-05-17 13:49:32.479 Python[1692:36892] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
ignaciobarrientos@MacBook-Pro-de-Ignacio DCComilon % 

Cabe destacar que ya probé la funcionalidad de pygame con otros códigos y funciona correctamente.

Espero me puedan ayudar, puesto que sin esto, no soy capaz de hacer esta pregunta :(

**Comment by dfloreaa** [comment]
Hola, te recuerdo que la visualizacion se hace desde `main.py`, no `visualization.py`. El problema esta en el retorno de tu funcion A* y/o de tu implementacion en Python.

Aqui alguien tiene un mismo problema y le recomiendan instalar los certificados para su version de Python desde python.org
https://discussions.apple.com/thread/255171260?answerId=259758134022&sortBy=best#259758134022

Saludos

**Comment by Naktraker** [comment]
Estimado,
Quizás me expresé mal en mi mensaje anterior, pero en la pregunta 2 no he implementado absolutamente nada, por lo que no podría ser el retorno de la función A*, solo estoy ejecutando el código que se nos entrega y aquello no funciona, ahora sin ningún cambio, es decir, tal como se descarga de GitHub.

Por otro lado, intenté lo que se indicaba en el foro de discusión, pero no funcionó, además de que he estado intentando por más de 6 horas (efectivas) de que funcione el código de la pregunta 2, sobre cosas que se supone que deberían venir listas, llegar y ejecutar. Lamentablemente no tengo acceso a un computador con Windows, por lo que no se que hacer al respecto, porque si se que en windows funciona. Cabe destacar que también instalé una máquina virtual (Parallels) en mi pc y tampoco funciona correctamente y tampoco puedo particionar el disco, puesto que la página Azure, que entrega licencias de windows por parte de la universidad me indica que no tengo acceso con las credenciales de la Universidad. Considerando todo lo anterior, y que no es un problema que sea de mi responsabilidad (no obstante igual intenté arreglarlo de manera intensiva y por muchas horas, durante varios días), qué puedo hacer? Dado que sin aquello no puedo hacer la pregunta?
