### ISSUE TITLE
[T3]P3.3 posible error de enunciado

### ISSUE THREAD

**Issue by Consolo0** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#43]
Hola, esperando que se encuentren bien, en la pregunta 3 actividad 3, nos dice que ocupemos alpha-beta y repitamos el experimento de la **actividad 3**, pero cual es el experimento de la actividad 3, solamente nos piden implementar alpha-beta nunca se habla de un experimento. Saludos.

**Comment by javiermarhuich** [comment]
Hola, no soy ayudante, pero en la primera versión del enunciado la Actividad 3 era la de los dos bots Minimax jugando entre ellos (la que decía "Profundidades distintas"), así que es posible que se trate de realizar esa parte pero ahora agregando las podas.

Saludos!

**Comment by Consolo0** [comment]
Muchas gracias!

**Comment by dfloreaa** [comment]
Hola, lo que comenta el compañero, fue un error al actualizar el enunciado.

Saludos
