### ISSUE TITLE
Duda 2.1 con expansions

### ISSUE THREAD

**Issue by melpony23** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#44]
Hola! tengo una duda, porque en el dfs se empieza con expansions = 1?

**Comment by melpony23** [comment]
y no con expansions = 0? que me hace más sentido que inicie con nodos que aun no se han expandido.

**Comment by dfloreaa** [comment]
Hola, tienes razon, aunque no deberia hacer gran diferencia.

Saludos ☺️
