### ISSUE TITLE
[T3] Duda implementación algoritmo RBFS

### ISSUE THREAD

**Issue by nonoam** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#45]
Hola tengo una consulta con la implementación del algoritmo RBFS. Dado que en el pseudo código indica que se debe entregar la variable f_limit como uno de los parámetros de la función. ¿se puede agregar dicho parámetro a la función o esto lo debemos implementar de otra manera? 
Pregunto dado que en el enunciado mencionan que los algoritmos se evaluarán con test-cases, entonces me quedaba la duda si solamente nos debemos preocupar de que el retorno fuera el correcto pudiendo modificar otros elementos del código, o es estrictamente necesario que no modifiquemos el código de `main.py` o parámetros de las funciones entregadas, la clase Cell entre otros.

**Comment by jadelanoa** [comment]
Tengo la misma duda.
