### ISSUE TITLE
Visualización DCComilon

### ISSUE THREAD

**Issue by adriana-salgueiro** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#48]
Me sale el siguiente error al hacer correr el main.py: Podrías darme una mano?
![dccomilon](https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/85044032/80d80b85-daf3-4632-bef3-93498d3c8325)

**Comment by pedrozavalat** [comment]
Holaa!, no soy ayudante pero por lo menos para utilizar la visualizacion tienes que descargar pygame. Solo debes hacer pip3 install pygame o pip install pygame en la terminal

**Comment by luisramirezzg** [comment]
Me sumo a esta duda. Ya corrí pip3 install pygame o pip install pygame y aún me aparece el error.
<img width="756" alt="Screenshot 2024-05-20 at 18 29 00" src="https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/76630125/8e4aabe8-dd6f-48a5-8e4c-3646d82c0439">
