### ISSUE TITLE
Duda ppt 3

### ISSUE THREAD

**Issue by rvcruz** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#5]
Hola, en el ppt de la clase 3, pagina 12.
En el punto 2 debería decir Head <- Body?

Por lo que entiendo, Tail refiere a las constantes de un predicado o atomo:

Head <- Body(Tail)

Por favor corregir si estoy mal, saludos!

**Comment by dfloreaa** [comment]
Hola, hasta donde tengo entendido ambos términos (Body y Tail) estan siendo utilizados bajo un mismo significado y de forma intercambiada. De todos modos, lo notifique al profesor para ver que opina.

Saludos :)
