### ISSUE TITLE
[Excel notas] Problema con visualizar cupones

### ISSUE THREAD

**Issue by B-Birb** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#51]
Hola! Tengo un problema en el excel de resumen del curso. No puedo ver los cupones que he usado porque los de la tarea 2 no se están mostrando correctamente :( Adjunto imagen.  

![image](https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/22687150/583dbc20-8543-4977-ab5d-ce80464acf3a)

Saludos y buena semana!

**Comment by dfloreaa** [comment]
Hola, el excel ha sido actualizado. Saludos ☺️
