### ISSUE TITLE
[T4] Columna "days_since_last" del dataset

### ISSUE THREAD

**Issue by isufan** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#55]
Hola,

Tenía la duda sobre qué significa la columna "days_since_last" del dataset y confirmar si fue agregada por el equipo docente, ya que en Kaggle no aparece.

Gracias de antemano.

**Comment by dfloreaa** [comment]
Hola @isufan, si, me falto comentarlo en el enunciado 😅

La columna `days_since_last` indica el numero de días que han transcurrido desde el ultimo sismo en una misma ubicación (dada por la columna `state`). La compute de manera manual.

Mucho éxito con tu tarea! ✨
