### ISSUE TITLE
Importación librerias

### ISSUE THREAD

**Issue by adribastiasm** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#56]
Hola! Se pueden importar más librerías o tenemos que usar solo las que nos dan?
Gracias de antemano.
Saludoss

**Comment by dfloreaa** [comment]
Hola, depende de para que, cuéntame

**Comment by fuaman22** [comment]
Hola, yo tengo la misma duda, me gustaría usar esta libreria [iso3166-2](https://pypi.org/project/iso3166-2/) para limpiar los datos. ¿Puedo usarla?

**Comment by dfloreaa** [comment]
@fuaman22 si, no hay problema. Asumo que es para generar una nueva columna usando latitud/longitud? Recuerda que debes fundamentar el uso de esta nueva columna para llevar a cabo la predicción y por que si provee ganancia de información! (y, de ser necesario, encodearla, ya sea de manera ordinal o one-hot)

**Comment by manuel-2112** [comment]
Se puede ocupar imblearn.over_sampling, para balancear los datos con el metodo SMOTE??

**Comment by dfloreaa** [comment]
Hola @manuel-2112, recomiendo no usarlo. La idea de esta tarea es que trabajen con un dataset desbalanceado precisamente para reportar los problemas que esto puede generar.

Saludos
