### ISSUE TITLE
Duda con la columna tiempo

### ISSUE THREAD

**Issue by czamoraz** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#57]
Hola!

Tengo una duda con la unidad de medida de la columna tiempo, ya que en Kaggle dice que se mide en milisegundos y que mide el tiempo del evento, pero las cantidades son demsiado grandes y llegan a no tener sentido con el evento (que vendría a ser un sismo), entonces mi pregunta es: ¿Es normal que los números sean tan grandes?

**Comment by dfloreaa** [comment]
Hola, corresponde a la fecha en que ocurrió el sismo desde 1970 [aqui mas detalles al respecto](https://en.wikipedia.org/wiki/Unix_time#:~:text=Unix%20time%20is%20a%20date,January%201970%2C%20the%20Unix%20epoch.).

Saludos ☺️
