### ISSUE TITLE
[T4] Chequeo de desbalance de clases

### ISSUE THREAD

**Issue by isufan** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#58]
Hola,

Quería saber si en la 2.1.3 tenemos que hacer el chequeo de desbalance de clases para todas las columnas, o podemos escoger cuáles chequear. Pregunto porque algunas columnas tienen variables cuantitativas donde no creo que tenga sentido calcular la distribución por clase, a menos que se haga con intervalos.

Gracias de antemano!

**Comment by dfloreaa** [comment]
Hola, el chequeo es para las clases que buscamos predecir, es decir magnitud y tsunami.

Saludos ☺️
