### ISSUE TITLE
[T4] Entrenar modelos

### ISSUE THREAD

**Issue by adribastiasm** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#59]
Hola! Para la parte 2.4, al entrenar los modelos por primera vez debemos poner hiperparámetros específicos como en la ayudantía? O usar los hiperparámetros que tiene cada modelo por defecto?
Saludos!

**Comment by dfloreaa** [comment]
Hola, usa los hiperparametros por defecto.

Saludos ☺️
