### ISSUE TITLE
[Tarea 1] Parte b y c

### ISSUE THREAD

**Issue by Martoxp** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#6]
Revisando la tarea se me generó una duda entorno al enunciado de estas dos preguntas
En ambas se nos pide listar cosas, es decir: nombrar actividades o problematicas
En este sentido yo fui muy literal y solo las deje mencionadas, pero no se si tambien deben estar acompañadas de una pequeña explicación de que es cada activdad o problematica

**Comment by dfloreaa** [comment]
Hola, con nombrarlos esta bien. Disculpa lo tardía de la respuesta, pero es para que no quedes con dudas al respecto.

Saludos :)
