### ISSUE TITLE
[T4] X_train y X_test

### ISSUE THREAD

**Issue by isufan** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#60]
Hola! 

En la parte 2.2.6, nos piden definir un único `X_train` y `X_test` sin las columnas `tsunami` y `magnitude`. Sin embargo, estimo que la magnitud podría ser un factor importante a la hora de predecir la ocurrencia de un tsunami. ¿De todas maneras tenemos que definir un único `X_train` y `X_test` para ambas tareas (clasificación de tsunamis y regresión de la magnitud) o se pueden crear matrices diferenciadas para cada tarea?

Saludos.

**Comment by dfloreaa** [comment]
Hola, si, la idea es no considerar cada atributo para hacer las predicciones, si gustas, puedes comparar los resultados con/sin el uso de cada columna.

Saludos ☺️

**Comment by dfloreaa** [comment]
_Spoiler: Una de las columnas tiene alta correlación con la magnitud, por lo que no nos aporta nueva información_

**Comment by isufan** [comment]
> _Spoiler: Una de las columnas tiene alta correlación con la magnitud, por lo que no nos aporta nueva información_

Toda la razón, no se me había ocurrido verlo de esa forma. De esa manera no afectaría dejar afuera `magnitude` de las matrices X. Gracias!

**Comment by NicoJGutierrez** [comment]
Hola! Una duda de follow up: Estaría mal si utilizo la columna y_train_magnitude y la columna y_test_magnitude junto con las tablas X_train y X_test para entrenar y testear el clasificador de tsunamis?
(pasa que ya lo tenía hecho así y quiero saber si me puedo ahorrar cambiar lo que ya tengo hecho)

**Comment by dfloreaa** [comment]
> Hola! Una duda de follow up: Estaría mal si utilizo la columna y_train_magnitude y la columna y_test_magnitude junto con las tablas X_train y X_test para entrenar y testear el clasificador de tsunamis? (pasa que ya lo tenía hecho así y quiero saber si me puedo ahorrar cambiar lo que ya tengo hecho)

Hola @NicoJGutierrez recomiendo no hacerlo, entrena tus clasificadores/regresores sin esas columnas y si gustas, hazlo con ellas también. La idea es tener consistencia entre los resultados que todos obtengan para la corrección,
