### ISSUE TITLE
[T4] Sobre el muestreo de datos

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#61]
Buenas tades!
en la sección 2.2.1 se nos pide investigar sobre métodos para enriquecer la dataset
mi pregunta es: además de esto, debemos implementar una de las técnicas que investigamos?

porque sino el desbalance sigue presente, al menos que esa sea la idea

muchas gracias :D

**Comment by dfloreaa** [comment]
Hola, no, la idea es solo identificar técnicas y luego estudiar resultados cuando se entrena un modelo y no se considera el balance de clases.

Hubiese sido un ejercicio interesante comparar los resultados con/sin aumentación de datos, siéntete libre de hacerlo si gustas, pero no será evaluado.

Saludos ☺️

**Comment by TomasRiquelme** [comment]
supeeer,muchas gracias Dani :)
