### ISSUE TITLE
[T4] Apartado 2.7

### ISSUE THREAD

**Issue by dvictorerol** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#63]
Hola, en el apartado 2.7 dice lo siguiente:

"Con los datos de **entrenamiento**, realiza una predicción de regresión con los modelos de KNN, árboles de decisión, Random Forest y SVM."

Supongo que debería decir de "testeo",  o no? es que no me hace mucho sentido realizar la predicción con los datos que fueron usados para el entrenamiento.

**Comment by dfloreaa** [comment]
Hola, si, se refiere a los de testeo. Habiendo entrenado los modelos de regresión sobre los datos de entrenamiento.

Saludos ☺️
