### ISSUE TITLE
[T4] Uso de fit_transform

### ISSUE THREAD

**Issue by czamoraz** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#65]
Hola!

Leyendo la documentación de StandardScaler y revisando algunas soluciones presentes en stackoverflow me di cuenta que fit_transform hace lo mismo que fit y después transform. Mi duda es, si es que cito esto desde donde lo vi, puedo usarlo? O necesariamente tengo que hacer fit y después transform?

**Comment by dfloreaa** [comment]
Hola, si, efectivamente hacen lo mismo (solo te ahorras una linea de código). Puedes usar el método que gustes, aunque te recomendaría seguir lo recomendado en el enunciado por facilidad a la hora de corregir.

Saludos ☺️
