### ISSUE TITLE
Dataset T5 

### ISSUE THREAD

**Issue by adribastiasm** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#66]
Hola!! Se puede usar más de un dataset?? Por ejemplo, 2?
Saludos!

**Comment by dfloreaa** [comment]
Hola @adribastiasm, depende de la tarea que desees desempeñar, aunque no debería haber problema siempre y cuando su uso sea correcto.

Podrías entrar un poco mas en detalle sobre por qué la necesidad de dos?

Saludos ☺️✨

**Comment by adribastiasm** [comment]
Es porque con la tarea que tengo pensada los dos datasets se complementan o sirven para que la tarea funcione. Pero también está la posibilidad de usar un solo dataset y explicar la ausencia del otro como posible mejora, qué sería más recomendable hacer?

**Comment by dfloreaa** [comment]
Hola, recomendaría usar ambos entonces. Recuerda fundamentarlo bien en el informe!

Saludos ☺️
