### ISSUE TITLE
sobre referencias a ayudantias en la tarea 5

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#67]
buenas tardes!
creo que tengo más o menos clara lo teorico de CNN que se explica en la ayudantia 13, pero tengo problemas en entender lo que hace el código del ipynb en la parte donde se crean las capas.
O sea, entiendo que es para crear la estructura, pero no veo como yo podria variar alguno de esos valores para crear mi propio modelo.

Mi pregunta va siendo: ¿puedo usar ese código para crear mi modelo CNN? dejaria especificado que lo usé de esa ayudantia

**Comment by dfloreaa** [comment]
Hola, si. La idea es que innoven en la aplicación que dan al modelo, no tanto en la estructura en si.

Saludos ✨
