### ISSUE TITLE
Sobre algoritmo a usar

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#68]
Buenas tardes
En el enunciado se habla de investigar de algunos métodos para hacer vision por computador/procesamiento de lenguaje natural

Si mi proyecto es de vision por computador:
Significa que puedo usar otro metodo que no sean redes neuronales?

Muchas gracias

**Comment by GonzaloFuentes1** [comment]
Hola, @TomasRiquelme la idea es que ocupen lo aprendido en las últimas sesiones de ayudantía. En tú caso, para un proyecto de visión por computador seria útil usar un clasificador CNN.
¿Qué clasificador tienes pensado utilizar? Existen modelos más avanzados que invitamos a probar, pero con un CNN bien construido y usando técnicas de preprocesamiento de imágenes debería ser más que suficiente.

Saludos  ☺️✨

**Comment by TomasRiquelme** [comment]
yaa perfecto, había encontrado una forma de usar algorimos SVC para clasificar imagenes, y me funcionó bien y todo la implementación.
Pero si tengo que usar CNN está bien
muchas gracias :D
