### ISSUE TITLE
[T5] Selección del Dataset para Tarea 5 (tema: visión por computadora)

### ISSUE THREAD

**Issue by jadelanoa** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#69]
Hola, tengo un par de dudas sobre la Tarea 5.

Después de estudiar el tema (visión por computadora), decidí utilizar el dataset de Kaggle **A-Z Handwritten Alphabets**, que es similar al dataset MNIST de dígitos escritos a mano (utilizado en la ayudantía 12). Tengo algunas preguntas y dudas sobre la adecuación y la complejidad de esta elección para los propósitos de la tarea.

**Preguntas:**
   - ¿Es apropiado el dataset **A-Z Handwritten Alphabets** para los objetivos de la tarea, considerando que es similar al MNIST pero con 26 clases en lugar de 10?
   - ¿Habría algún inconveniente en combinar este dataset con el MNIST para incrementar el tamaño del dataset y tener una mayor variedad de datos?
   - Utilizando Keras, siento que programar y entrenar una CNN para este dataset es relativamente sencillo. ¿Es este enfoque demasiado simple para la tarea, o cumple con los requisitos esperados en términos de dificultad y profundidad del proyecto?
   - ¿Hay algún aspecto específico que debería considerar o agregar para asegurarme de que el proyecto cumpla con los requisitos esperados?

Tengo pensado experimentar con diferentes modelos (arquitecturas y optimizaciones) de CNN, utilizando preprocesamiento de datos y augmentación para mejorar el rendimiento y lograr una buena precisión. ¿Esta propuesta cumple con los requisitos esperados en términos de dificultad y profundidad del proyecto?

**Comment by dfloreaa** [comment]
Hola, la implementación de tu tarea parece ser muy similar a la ayudantía. De hecho, existe un dataset llamado [EMNIST](https://www.kaggle.com/datasets/crawford/emnist) que corresponde a una combinación de MNIST con el dataset que comentas.

Todo lo que comentas respecto a tu trabajo lo encuentro bien, pero te recomendaría llevarlo a cabo en un problema de un dominio distinto, con otro set de datos de otra naturaleza (i.e. un clasificador de fotografías de animales), o mediante otro uso mas allá del visto en la ayudantía (i.e. lectura de frases escritas a mano mediante la segmentación y clasificación de cada letra).

Cualquier duda al respecto, no dudes en contactarme por aquí :)
Saludos ✨
