### ISSUE TITLE
Consulta de codigo "bodega"

### ISSUE THREAD

**Issue by TomasRiquelme** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#7]
buenas tardes!
tengo una pregunta sobre esta parte del código:
% cada robot debe escoger para donde moverse en cada tiempo
% exec(R,A,T): el robot R ejecuta A en T

1 {exec(R,A,T-1) : action(A)} 1:- robot(R), time(T).

Tengo dudas sobre el T - 1; que todavia no me hace sentido como repercute en el programa.
Por ejemplo:
on(R,X+1,Y,T+1) :- exec(R,right,T), on(R,X,Y,T), time(T+1).

Aqui entiendo que se cambia la posición dependiendo del exec, de la posición y de si el tiempo T + 1 existe.
Pero, en la linea con **; no se retornaria un exec(R,A,T- 1)? Si estoy en un tiempo T y tengo un exec que tiene un T - 1; no entiendo como se puede cumplir la linea sin **.
Investigue con chat gepeto y vi que tenia que ver con que es como si "en T - 1 se tomara la decision de que hacer en T". Y le veo sentido, pero aun así no entiendo como funcionara el codigo con un on en T y un exec en T -1 :c

Grax de antemano, siento que no puedo hacer la tarea hasta entender en verdad como funciona jeje

**Comment by dfloreaa** [comment]
Hola, la idea de ello es que el robot terminara su movimiento en un instante $T_f$, por tanto, todos los instantes de tiempo antes de ese $T_f$ $(T_{f-1}, T_{f-2}, ..., T_0$ tendran una **unica** accion asociada. En otras palabras, siempre que exista un tiempo $T$, se ejecutara una accion en un instante de tiempo anterior.

Espero que se entienda, saludos :)

**Comment by TomasRiquelme** [comment]
perfectoooooooo, mushas gracias :3
