### ISSUE TITLE
[T5] Duda sobre originalidad de los proyectos

### ISSUE THREAD

**Issue by SVenegasA** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#70]
Saludos
Mi duda es algo simple, ¿Es necesario que haya originalidad en los proyectos?, o ¿Solo basta con que el código sea creado por nosotros? Al menos a mí se me ocurrió el crear un algoritmo que pueda usar la visión por computadora para detectar si una imagen fue creada por IA o es original (o real), pero veo que ya hay muchos proyectos así por kaggle :c
Otra cosa, si el data set es de solo imágenes, ¿Cómo se considera si es un data set limpio, o listo para ser usado como datos de entrenamiento?

**Comment by dfloreaa** [comment]
Hola, no hay problema. La mayoría de las bases de datos disponibles ya fueron utilizadas para múltiples otros propósitos, por lo que no les pedimos reinventar la rueda.

Ahora bien, si se espera un componente de innovación en su trabajo, no solo a nivel de código, si no también a nivel de implementación, estructura y motivación. Además de implementar una solución (que debe ser propia, aunque el problema no lo sea), deben ser capaz de justificar su relevancia y propósito.

Saludos ✨
