### ISSUE TITLE
T5: Imagenes y caracteristicas extraidas

### ISSUE THREAD

**Issue by Diego-Galleguillos** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#71]
Para mi proyecto de visión por computador extraje características de textura (LBP) y clasifique las imágenes con un KNN de 3 vecinos obteniendo un accuraccy de 92%, quería consultar si es necesario que suba un archivo con las imágenes y con las características guardadas (para que puedan ejecutar el archivo sin tener que esperar la extracción de las 5800 imágenes) o si solo es necesario subir el pdf y el archivo .ipynb con todas las celdas ejecutadas.

**Comment by dfloreaa** [comment]
Hola, con tener las celdas corridas en el notebook que entregues y que funcione (asumiendo que se tiene la base de datos original descargada) esta bien.

Saludos ☺️

**Comment by Diego-Galleguillos** [comment]
Hola, la base de datos es: https://www.kaggle.com/datasets/muhammad0subhan/fruit-and-vegetable-disease-healthy-vs-rotten
pero no la logre cargar de forma automática dentro del código por lo que la descargue y ocupe dos carpetas de imágenes:
![tarea](https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/89211159/744886b3-9b7a-42c8-8134-d48926b6a809)

Esta bien asi o debo subirlas de alguna forma con el archivo?

**Comment by dfloreaa** [comment]
Hola, esta bien
