### ISSUE TITLE
[T5] Procesamiento de lenguaje natural

### ISSUE THREAD

**Issue by PelayoF** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#72]
Me entro la duda y quería confirmar, pero los números si se consideran dentro del lenguaje natural o no?

**Comment by dfloreaa** [comment]
Hola, solamente si hay palabras incluidas dentro del resto del texto, si.

**Comment by PelayoF** [comment]
Ok. Tengo una duda, en el google colab me estoy quedando sin ram para mi codigo, no se si esto es normal o es porque estoy haciendo algo mal, ocurre cuando estoy entrenando el modelo

**Comment by dfloreaa** [comment]
Hola, es probable que estes cargando todos los datos a la vez en lugar de hacerlo por partes. Te recomiendo leer un poco sobre el entrenamiento en batches para un modelo.
