### ISSUE TITLE
[T5] Trabajo de datos para Visión por computador

### ISSUE THREAD

**Issue by cstappung** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#74]
Hola!

Tenía dudas sobre el trabajo de datos para el caso de Vision por computador, ya que en el enunciado dice:
"...desbalance de clases, análisis cualitativo y trabajo de los datos nulos."
Y no sé exactamente como podría trabajar datos nulos si es que mi data set de imágenes no los tiene.
Tambien, quiero preguntar que se espera de análisis cualitativo.

¡Saludos, Gracias!

**Comment by dfloreaa** [comment]
Hola, simplemente no lo haces, menos pega ☺️ (recomiendo comentar que se estudio el dataset y se encontro que no habian datos nulos en el informe)

Un saludo ✨
