### ISSUE TITLE
[Tarea 1] Consulta acerca de los identificadores de las piezas torre y alfil

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2613-Inteligencia-Artificial-2024-1/Syllabus#8]
Hola!

Leyendo el enunciado, no me queda muy claro para qué es el identificador que se le asigna a la torre y al alfil. ¿Por qué a estas dos piezas se le asigna un identificador, y al resto no?

**Comment by dfloreaa** [comment]
Hola, se le otorgan identificadores a estas piezas debido a que tienen lineas de ataque de largo mayor a uno que pueden ser interrumpidas por otras piezas.

![image](https://github.com/IIC2613-Inteligencia-Artificial-2024-1/Syllabus/assets/62019645/70754259-de96-4d2d-b827-c3f7e315f90a)

En el siguiente ejemplo el alfil tiene su linea de ataque superior izquierda bloqueada por otro peon.

Un problema que surge es que si tenemos multiples alfiles en el tablero, como sabemos cual de sus lineas de ataque bloquear? Es por eso que les otorgamos un ID unico a cada uno.

Saludos ☺️

**Comment by Francisco-Aguilera-xd** [comment]
Ahhh vale, muchas gracias por la aclaración
